### ISSUE TITLE
Chance dosnt not work on milestones

### ISSUE THREAD

**Issue by fenix12585** [imWillX/CrateReloaded#101]
Hello,

I am trying to use the chance option in milestone rewards and it does not effect anything. Instead the player gets the reward every time they hit the milestone. The chance option does work in standard rewards, just not the milestones. I am using Spigot 1.11.2 and and the latest version of your plugin.

Thanks!

**Comment by imWillX** [comment]
Hello,

Sorry, i'm not sure what a milestone reward is. Please reopen the issue if this is something you would like to see added.
