### ISSUE TITLE
Crates can be opened with full inventory

### ISSUE THREAD

**Issue by ItsHarry** [imWillX/CrateReloaded#103]
Crates can be opened even if the player's inventory is full, causing the reward to be lost.

Also, items can be picked up while the reward is being rolled, causing the inventory to become full and reward being lost.

**Comment by imWillX** [comment]
Duplicate #36

**Comment by imWillX** [comment]
I'll be able to fix the first issue however the second issue will require another system.

**Comment by FrozenBeard** [comment]
Woah, are you joking? people could pay for a key and then if they have a full inventory they will loose it!???

**Comment by imWillX** [comment]
Release: 1.3.94
Players will receive an error message upon attempting to open a crate with a full inventory.

Language File
```inventory.full=%prefix%Your inventory is full!```
