### ISSUE TITLE
Changes to Roulette type

### ISSUE THREAD

**Issue by EHAndrew** [imWillX/CrateReloaded#107]
I found that while they look really cool, roulette crates do not support multiple rewards, so the min/max rewards setting is useless. It would also be nice to be able to set the hang time that the reward is displayed before dropping it into the player's inventory (or even infinite, so that the player has to actually close out of the GUI, like exiting a chest GUI). Lastly, the roulette type visual is just begging for sounds (onOpenSound:?).

**Comment by imWillX** [comment]
Hey there,

Thanks for the suggestions. We do have opening and roulette sounds. Please check your crate.yml.
