### ISSUE TITLE
CrateReloaded CrateInteractEvent is overriding all GUI menu click / drag interactions.

### ISSUE THREAD

**Issue by mibby** [imWillX/CrateReloaded#111]
CrateReloaded 1.3.90-alpha-1

@imWillX It seems the new update for CrateReloaded is overriding all forms of GUI menus. It thinks opened interfaces from other plugins are a crate.

E.g.
When someone tries to use ```/trash``` or ```/uncrafter``` from the VirtualPack plugin (https://github.com/Siguza/VirtualPack), a message shows up in chat: "Crate->Please select a crate" while the items the player is trying to move into the GUI menu to destroy / uncraft get cancelled and still remain in their inventory.

Version 1.3.88 works fine.

**Comment by imWillX** [comment]
Will take a look.

**Comment by imWillX** [comment]
Fix implemented. Will be released this weekend.
