### ISSUE TITLE
CSGO roulette final item is not part of the scroll.

### ISSUE THREAD

**Issue by mibby** [imWillX/CrateReloaded#113]
Would it be possible to have the final reward item part of the scroll order? Otherwise it just seems to give false hope (according to my players) when it just pops up out of nowhere as the selected item.

Example scroll.
```
1-2-3-*4*-5-6-7
0-1-2-*3*-4-5-6
7-0-4-*2*-3-4-5
6-7-0-*4*-2-3-4
```

Edit: Maybe it is just the far left side that is lying.
https://i.gyazo.com/e244378b4fd8006e1f6c64cf75574060.mp4

As when it starts to slow down and you see something good appear, you get excited but then it just goes away.

**Comment by imWillX** [comment]
It might be the far left side that is lying. I'll probably rework the animation.
