### ISSUE TITLE
No longer able to look at a crate location and remove it with '/cr remove'.

### ISSUE THREAD

**Issue by mibby** [imWillX/CrateReloaded#117]
CrateReloaded 1.3.91-alpha-1

Looking at a defined crate location and typing ```/cr remove``` no longer removes that crate. It outputs in chat ```Incorrect number of arguments```.

Was working fine with v1.3.88.

**Comment by imWillX** [comment]
Hiya Mibby,

It now requires an additional input which is the crate name. This is to handle support for multiple crates per location.
