### ISSUE TITLE
One-time Reward

### ISSUE THREAD

**Issue by portaljumper007** [imWillX/CrateReloaded#12]
The option to make it so if you get something in that crate you can never get it again in THAT crate or in all crates or within a certain amount of time or until something for example.

**Comment by iAmWillX** [comment]
Will probably add a tag as one-time:()

**Comment by imWillX** [comment]
[Update](https://www.spigotmc.org/resources/mystery-crate-cratereloaded-for-the-finest-servers.3663/update?update=77613)
