### ISSUE TITLE
[1.3.95b] Plugin doesn't load

### ISSUE THREAD

**Issue by aurel85** [imWillX/CrateReloaded#127]
Hi,

With the version 1.3.95b the plugin doesn't load : 
https://sandbox.fr/images/uploads/original/1498560097.png

In the console : 
https://pastebin.com/AjddrTc9

I use PaperSpigot 1.12.

**Comment by imWillX** [comment]
Could you DM me your crate.yml?

**Comment by imWillX** [comment]
Could you DM me your server setup?

**Comment by aurel85** [comment]
My plugins : https://www.dropbox.com/s/1bi70gi3us5muz7/plugins.png?dl=0
My CrateReloaded config : https://www.dropbox.com/s/a687cpg4aapetwf/config2.yml?dl=0
My file crate.yml : https://www.dropbox.com/s/hkk8q3uebxzrrmh/crate.yml?dl=0

**Comment by imWillX** [comment]
Add this to your config.yml
```
# Chance Format
# ex: #.## 1.23
#
display:
  chanceFormat: '#'
```

**Comment by aurel85** [comment]
Everything is ok now, thank you !
