### ISSUE TITLE
Error :(

### ISSUE THREAD

**Issue by TheSodaPopPanda** [imWillX/CrateReloaded#130]
Hi, I just updated your plugin and now I am unable to set crates or perform any commands.

https://pastebin.com/3am9tP5d

**Comment by imWillX** [comment]
Please provide your crate.yml and config.yml.

**Comment by TheSodaPopPanda** [comment]
HI there, Sorry for the late response been at work all day! 

http://www.mediafire.com/file/4snpzs7pd2n2vsm/crate.yml

http://www.mediafire.com/file/o4rc2atfzt2kv3h/config.yml

**Comment by TheSodaPopPanda** [comment]
um... hello?

**Comment by TheSodaPopPanda** [comment]
no answer... was it me in my config I have only started having a problem after I updated though...?

**Comment by imWillX** [comment]
Hey there, I released an update.

Your config.yml was missing a decimal value which resulted in the plugin not loading.

If it still persist, please reopen the issue.
