### ISSUE TITLE
1.8 URGENT ISSUE

### ISSUE THREAD

**Issue by AMinecraftDev** [imWillX/CrateReloaded#132]
I'm using the latest version **(1.3.96)** and I get spammed with this error (20,000+ lines of error in less then 10 minutes):

https://hastebin.com/qujekomada.md

**Comment by imWillX** [comment]
I released another update. Please try that and let me know if the issue still occurs.
https://www.spigotmc.org/resources/mystery-crate-cratereloaded-for-the-finest-servers.3663/history
