### ISSUE TITLE
Support for adding NBT tags to an item display.

### ISSUE THREAD

**Issue by mibby** [imWillX/CrateReloaded#133]
Would it be possible to allow setting an item with a specific nbt tag in the display? I use a resource pack for custom items that have a specific damage state with the unbreakable NBT tag. I'd like to get the custom item in the rotation display but the item requires the unbreakable tag to show up.

**Comment by mibby** [comment]
Bump. ^^

**Comment by mibby** [comment]
Bump. ^^

**Comment by mibby** [comment]
Bump. ^^

**Comment by imWillX** [comment]
Sorry for the lack of updates. I'm currently rewriting internals for API. Design decisions for this feature is on a standstill. More info below. 

I'm currently stuck between two design decisions. Since we're using a custom parsing system, we could continue implementing data this way but it'd tough to add future attributes in both design and readability. Our other option is to completely scrap our parsing system, then rewrite it similar to essentials system. 

Our Parsing Format - item:(id amount name lore data)
Essentials Format - /i bow 1 name:Mighty_twang lore:Through|the|ages

Of course, if we do decide to change, we have to write a converter to the new config. (Some people have 2000 lines in there config) 

Our other option is to continue as is.

**Comment by mibby** [comment]
Personally, I'm a fan of your custom parser because you support specifying head data as well as adding a glow enchantment on items. If that could just be extended to allowing NBT tags, it would be perfect. But I do understand why you would want to move towards simplifying the system.

**Comment by mibby** [comment]
Possible format suggestion for nbt tagging in the parser. You could have players specify which nbt tags to apply on an item via something like;

```display:(397:3 1 &aA_Head &f%chance% nbt:tag,tag2,tag3,tag4)```
Or instead ```flags:unbreakable,glow,hide``` etc.

Otherwise it may be better to just support the names of each NBT tag to allow for value setting. Such as;

```display:(397:3 1 &aA_Head &f%chance% unbreakable:1 hideflags:#, glow:1)```

Since some nbt tags do have specific value options.
The only useful flags I'd probably ever use though are glow, unbreakable, and hideflags. Most NBT flags are useless for item displaying so implementation of only the popular / useful ones should maybe be considered.

For reference.
https://minecraft.gamepedia.com/Tutorials/Command_NBT_tags
https://minecraft.gamepedia.com/Player.dat_format#Item_structure
https://minecraft.gamepedia.com/Chunk_format

**Comment by imWillX** [comment]
Base Values
```
display:(itemID:durability name:myName lore:lore1|lore2 skull:base64 color:r,g,b effect:haste power:1 duration:30 splash:true unbreakable glow )
```

Potions: #169 

Skulls: #97 

**MISC**

Enchanted Book
```
display:(403 1 17:1)
```

Enchanted Sword (with unbreakable)
```
display:(diamond_sword 1 17:1 18:1 unbreakable:true hide:true)
```

**Notes**
Removed Enchantment 300:1 from new parser.

**Comment by mibby** [comment]
Can't wait! :D

**Comment by mibby** [comment]
@imWillX How's 2.0 coming along? ^^

**Comment by mibby** [comment]
@imWillX Any update on NBT support / 2.0 news?

**Comment by imWillX** [comment]
It's taking a little longer than I expected.

I'll post more details once I have the time with what I have done, what I need to do, and what I can add in the future after 2.0. This will be edited later tomorrow.

**Comment by imWillX** [comment]
@mibby Thanks for waiting.

Our progress with 2.0:
**Done**

1.  Item/NBT Parser #133
2. Tab Completion
3. New Configuration Design with consistent casing #184 
4. GUI Animations are now reversible. i.e. CSGO / Reverse CSGO

**In Progress**

1. Website/Documentation
2. API Design/Implementation
3. Certain parts of the code base needs to be re-implemented.
4. Several of [these](https://github.com/Hazebyte/CrateReloaded/milestone/1)

**Comment by mibby** [comment]
Super excited for the changes and NBT support. Hopefully it won't be too much longer now! :)

**Comment by imWillX** [comment]
@mibby Are you available for testing? (Discord)

We're close to a R.C. assuming that some features are continually developed after I release 2.0.0.
