### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by SirZodiac** [imWillX/CrateReloaded#145]
Plugin keeps throwing this error when i try to setup a crate.. i have had the plugin for a while now and havent had any problems till now. I recently updated the plugin to the latest version whereas i have been running the other version on a 1.7.10 modded minecraft server. 

![image](https://user-images.githubusercontent.com/14103025/29399044-2f5db14a-82ed-11e7-9874-ec0f79ee759c.png)

**Comment by imWillX** [comment]
Included Reflection in 1.3.97.6.

Will be testing and releasing fix soon.
