### ISSUE TITLE
Leftover debug.

### ISSUE THREAD

**Issue by mibby** [imWillX/CrateReloaded#146]
CrateReloaded v1.3.96.6

@imWillX Leftover debug info is being outputted to console when a player opens a crate.

```
# Debugger (Developer Note: Disabled. ETA: N/A)
# Developing Use Only. Disable, if you do not want to recieve debug messages.
debug: false
```
```
[02:39:58] [Server thread/INFO]: player opened VoterCrate. Rewards: [Line: cmd:(/give %player% 3:1 32), chance:(120), display:(3:1 32 &a32_Coarse_Blocks! &f%chance%)
Items: 0, CMDs: 1, Slot: 0, Chance: 120.000000, One-Time: 0, Messages: 0
minC: 260.000000, maxC: 260.000000]
```

Specifically the bottom 2 lines.

**Comment by mibby** [comment]
I'm also assuming you didn't mean to publish the newest build as 1.3.96.6 with the last build being 1.3.97.5? Bit odd to go backwards in version numbers. :P

**Comment by imWillX** [comment]
@mibby 
Thanks, will be fixed.

**Comment by imWillX** [comment]
Updates
- File names are aesthetically now compiled to a date: yyyy-MM-dd. 
- No longer prints to console. Save the clutter! 
- Performance Update.

**Comment by mibby** [comment]
When's the update coming out? :P
