### ISSUE TITLE
Iron shovel in chest creates parsing error

### ISSUE THREAD

**Issue by redshadus** [imWillX/CrateReloaded#158]
Hi. I put in iron shovels into my config for a chest and each time I create the chest, it gives me a parsing error.

Config screenshot: https://gyazo.com/1621d1e7dfe847338289e8135b415bd7
Ingame screenshot: https://gyazo.com/aaa257b9d7c3d24ef3b6b66958633c31

**Comment by imWillX** [comment]
Please use item ids. Please keep in mind that the item requires an amount as well.

[CODE]item:(256 1), chance:(2)[/CODE]
