### ISSUE TITLE
Feature Request: %playerUUID%

### ISSUE THREAD

**Issue by klugemonkey** [imWillX/CrateReloaded#159]
Can you add %playerUUID% as a placeholder (String representation)?
I'm thinking to use in cmd similar to ...

/give %player% 383:95 1 {display:{Name:"Spawn Toto"},EntityTag:{CustomName:"Toto",CustomNameVisible:1b,id:Wolf,Age:-600000,Angry:0b,CollarColor:15b,OwnerUUID:"%playerUUID%"}}

to allow a Wolf egg to spawn a Wolf that is tamed for the specific player.

**Comment by imWillX** [comment]
Please check [https://github.com/imWillX/CrateReloadedAPI/blob/master/src/main/java/com/hazebyte/crate/api/util/Replacer.java#L48](here).

It will be released in CrateReloaded 2.0.0.

**Comment by klugemonkey** [comment]
Sweet!  Can't wait.

**Comment by klugemonkey** [comment]
Also,

 .replaceAll("%crateRewards", crate.getRewardString());

is missing % at end.

**Comment by imWillX** [comment]
Thanks!

We'll be fixing this.

**Comment by imWillX** [comment]
Thanks! We'll be closing this issue. 

Feel free to submit issues at the other repo for API implementation issues. https://github.com/imWillX/CrateReloadedAPI

This will be released for 2.0.0.
