### ISSUE TITLE
Broken logger as of v1.3.98

### ISSUE THREAD

**Issue by mibby** [imWillX/CrateReloaded#161]
CrateReloaded v1.3.98

The logger seems to be broken as of the latest update. I do not have logs older than 2017-09-19 in the logs folder with ```logger: true``` set in the config.

**Comment by imWillX** [comment]
Hey @mibby 

I'm aware and a fix is already out for an alpha build. Please check Discord!

**Comment by mibby** [comment]
Glad to hear. I rely on the Creative Control feature heavily, so I'll personally be holding off from updating to the alpha build for the time being.

**Comment by imWillX** [comment]
Released hotfix for logger.
