### ISSUE TITLE
API Improvements

### ISSUE THREAD

**Issue by glorantq** [imWillX/CrateReloaded#168]
It'd be nice if the API had methods to list crates, as currently, the only way to acquire Crate instances is through events.

*(x-post from Discord messages)*
![image](https://user-images.githubusercontent.com/17655680/31780012-d953d664-b4f4-11e7-861a-bf1fc7538ca3.png)

**Comment by imWillX** [comment]
https://github.com/imWillX/CrateReloadedAPI/blob/master/src/main/java/com/hazebyte/crate/api/crate/CrateRegistrar.java

We’re planning to document and write examples.
