### ISSUE TITLE
Block creative mode use

### ISSUE THREAD

**Issue by frizzbee30** [imWillX/CrateReloaded#170]
Hi, we want to now move a crate into creative world to give timed perm access etc as rewards. However it is fairly easy to duplicate the keys and then use them in the crate.

Could you add blocking of players in creative move from using keys? Currently we are looking at creating a forced gamemode survival area to host the chests, which is a bit long winded. 

Obviously we could block chest access etc altogether, but players do like to access them, or use our creative management to block players holding the stars in GM 1 mode. However when voting they could equally lose access to the keys if in GM 1 mode. 

We do have other plugins that block gm 1 access.

Thanks  :)

**Comment by imWillX** [comment]
Hey @frizzbee30 

Please enable creative-control in your config.yml. If it does not exist, please add the following...
```creative-control: true```

#5

**Comment by frizzbee30** [comment]
hi, I've added this to the config (rev 9), but it is still possible to use the keys while in creative mode?

Thanks

**Comment by imWillX** [comment]
Hey @frizzbee30,

Yes. Users won't be able to move keys but they'll be able to use the keys.

**Comment by frizzbee30** [comment]
Thanks  :)
