### ISSUE TITLE
Virtual Keys

### ISSUE THREAD

**Issue by ChimpGamer** [imWillX/CrateReloaded#176]
Hey,

I have a Creative server where I run CreateReloaded on. We want to use the plugin but our issue is that Creative Players can duplicate the keys. Is it possible to add Virtual Keys like tokens? They will be saved in a database or so.

I hope this will be added so I can use the plugin on the Creative server.

Kind regards,
ChimpGamer

**Comment by LogGits** [comment]
@ChimpGamer add:
`creative-control: true`
to your config file for CrateReloaded.

**Comment by imWillX** [comment]
#1 #4 #19 

We'll have a variation of virtual keys after I finish the API. I'm busy with other coursework atm. 

A solution to the creative issue is what @LogGits mentioned.
