### ISSUE TITLE
Recode: CrateReloaded 2.0?

### ISSUE THREAD

**Issue by imWillX** [imWillX/CrateReloaded#18]
CrateReloaded was built in August 2014 for Bukkit 1.7.10. Since then, I have learned quite a bit about the Bukkit API, and several parts of the plugin can be improved with the new knowledge that I have now. Additionally, if we were to update to Bukkit 1.8, we could use several new features like Holographics and Armorstands without dependencies. 

With that being said, I would like to rework the plugin in 1.8 to accommodate the new features of Minecraft. 

Current Plans:
Modularization
Command Tab Completition

update: Rip... time gets the best of you.

**Comment by mibby** [comment]
:+1:

**Comment by imWillX** [comment]
Currently, a rewrite is in progress.

We will be removing CS:GO and Roulette Crate from the type tag. Instead we will have animation tag so CSGO and roulette can be used on all types of crates instead of just keycrate.
