### ISSUE TITLE
Clean crate config suggestion

### ISSUE THREAD

**Issue by WizardPulse** [imWillX/CrateReloaded#21]
After spending a lot of time working with this plugin I'd really love to see a more clean crate config setup.

Here's what I propose in order for this to happen.

In the crates.yml you can split of different crate files into folders.

Example: This example is taken from DeluxeMenus and it'd be great for this plugin to do something like it.

crate_menus:
  donorCrates:
    file: donorCrates.yml
  normalCrates:
    file: normalCrates.yml

So that would create two crate config files which allows us the ability to make the crates config more compact and cleaner.

But than we'd also be able to link it off into it's own folder like so.

crate_menus:
  normalCrates:
    file: survivalCrates/normalCrates.yml
  donorCrates:
    file: survivalCrates/donorCrates.yml

I think having this ability would really allow for a clean crate config and would make it easier when creating lots and lots of crates.

Thanks :)

**Comment by iAmWillX** [comment]
Hey WizardPulse,

Funny thing is, I was actually thinking of making my crate setup like this. Definitely a good idea and something I would like to implement in the future.

**Comment by WizardPulse** [comment]
:+1: I guess two great minds do think alike.

I'm looking forward to seeing this being implemented. Keep up the great work.

**Comment by imWillX** [comment]
Will be included in the next update.
