### ISSUE TITLE
Variables Still dont work

### ISSUE THREAD

**Issue by Reeferx7** [imWillX/CrateReloaded#25]
The Variables still dont work on all messages. Here is a example what i mean:

![41fd586cd1d5430164a40140436cb500](https://cloud.githubusercontent.com/assets/8740881/12887469/2b5881ae-ce7d-11e5-8df5-f4e045115da7.png)

Same with others:
%cratename%: Display Name
%crateitemname%: Item Name
%keyitemname%: Key Item Name
%cratetype%: Crate Type

**Comment by iAmWillX** [comment]
These were added into the crate.yml reward messaging section.

Will work to get these into the messaging section.
