### ISSUE TITLE
Roulette Crate Update

### ISSUE THREAD

**Issue by imWillX** [imWillX/CrateReloaded#26]
Roulette Crate is in need of an update. If you have any ideas, list them below.
* Update Animation (Fast -> Slow)
* Players can re-enter animation after leaving menu
* Inventory Close

**Comment by imWillX** [comment]
**Update 4/23**
- Add Animation Speed
- Exit Handling: Players can reenter animation after exiting.
- Animation Closing: Inventory automatically closes on end.

**Comment by mibby** [comment]
@imWillX Can you go into detail regarding the animation update? CSGO crate rotation feels worse in version 1.3.70 than in 1.3.69. It stutters and chugs near the end. Whereas 1.3.69 is smooth throughout, even in slowing down.

Another thing I noticed is the flashing pattern (glass panes) does not have the random numbers in 1.3.70, whereas it does in 1.3.69. Could that have something to do with the worse animation?

**Comment by imWillX** [comment]
@mibby 
In Roulette Crates, it is improved where it starts off fast then ends slow. There might be stuttering issues but ill take a look at that.

Sadly my code didn't match my theory for CS:GO crates and despite multiple testing, I didn't catch the stuttering issue. It was supposedly to smooth the animation out over the period of seconds and near the ending, it would slow down dramatically emphasizing the reward (From the actual CS:GO Game).
 
The entire animation system was rebuilt to handle more animations. I rebuilt the whole foundation so I could add in more animations.
