### ISSUE TITLE
Allow crate messages to output to the server log.

### ISSUE THREAD

**Issue by mibby** [imWillX/CrateReloaded#27]
Currently crate messages do not output / save to the console log. Instead they are clientside messages only. Shouldn't some of the crate messages output to console / server log, such as when a user receives and uses a crate key?

**Comment by iAmWillX** [comment]
We currently do not log any of these. If you wish, we can add in logging to a text file.

**Comment by mibby** [comment]
Logging to a text file in the crates folder would suffice.

**Comment by mibby** [comment]
@imWillX Bump. Still would like for commands initiated by CrateReloaded to be logged in the main server log (as with all other commands) or somewhere else.

**Comment by imWillX** [comment]
@mibby Will try to include this in the next update.

**Comment by imWillX** [comment]
@mibby Feature finished. Will be included in the next update.
