### ISSUE TITLE
Lagg issue, low tps and performance...

### ISSUE THREAD

**Issue by maxlehot1234** [imWillX/CrateReloaded#28]
Hi, I just connect to my server and I see that I have 17 TPS...
Check here: http://timings.aikar.co/?url=15016613

MysteryCrate take too much ressource for playerinteractevent. 

Any way to fix this because a part of my server laggs come from your plugin :( I know it is weird, but it happens without reason or error...

Thank you and maybe a fix fast for this problem.

Have a nice day/night

**Comment by iAmWillX** [comment]
Hey Maxlehot1234,

Ill take a look into the interact listener.

**Comment by maxlehot1234** [comment]
I have this again and my tps drop to 14..... It is really bad and I don't know why it happen now, I changed nothing in the plugin for almost a week or two...

**Comment by maxlehot1234** [comment]
All my players are kick because nocheatplus thinkg that they hack but this is not true....Mysterycrate make TPS drop so all players bugs. They jump but nocheatplus thing they fly so it kick players for this....


It is very bad, I hope you fix this really soon because I lost players cause of this :(


Thanks again

**Comment by imWillX** [comment]
v78 should address this issue.

If there are anymore tps issues, please reopen the issue with timings.
