### ISSUE TITLE
Holographic Displays

### ISSUE THREAD

**Issue by imWillX** [imWillX/CrateReloaded#3]
Feature: Add Holographic Displays on top of your crate.

Purpose: Allow server owners to simply set a crate without any other configurations ingame.

Dependency: HolographicDisplays

**Comment by imWillX** [comment]
<pre>Crate:
    type: CSGOKEYCRATE
    displayName: '&7[&6My Crate&7]'
    holographic:
        - '&7[&6My Crate&7]'
        - 'Click the chest with a key!'</pre>

**Comment by Laos1996** [comment]
There is issue with it, not centered correctly beneath the crate, but to the left of it.
https://gyazo.com/1373c56d05acf594aa502afcc520c9e7

**Comment by imWillX** [comment]
@Laos1996 #44

**Comment by Laos1996** [comment]
Not centered again, as it is now infront of the crate
https://gyazo.com/573ac9da533dc588d8afa4b070183f4d

**Issue** is of now is that sometimes it blocks you from left/right clicking chests. (That's what holographic display usually does). Please make Holo display appear 1 block above the crate (that's what I have done so far manually)

**Comment by imWillX** [comment]
@Laos1996 Hmm, it centers for me. Ill give it another look.

**Comment by Laos1996** [comment]
Actually, it puts it one to the north of current location of crate
https://gyazo.com/80ab67c8efb34fa3ca6d55da9cdba248

**Comment by imWillX** [comment]
Hmm, I added one to fix the offset from the last version. Now I removed the one and it happens to be offset again.

**Comment by Laos1996** [comment]
I've updated HD just in case it wasnt that, I've moved from paperspigot to spigot latest I could find, could it be maybe some part of config I have to delete?

**Comment by imWillX** [comment]
Hey Laos,

Currently unable to reproduce the effects. Can you join our discord so we can schedule a time to test this?

Testing: 
![test](http://i.imgur.com/6olVG7G.png)

**Comment by imWillX** [comment]
**Update 4/23**
Found the issue.

If the crate's X value is negative, the crate is offset.

**Comment by Laos1996** [comment]
https://gyazo.com/28169c11853a8797894d97da0fae7116

They need to be elevated 1 higher!

**Comment by imWillX** [comment]
@Laos1996 No worries!
Ill increase y by 1. This will definitely be the last update regarding hologram positioning.
