### ISSUE TITLE
Problem opening crates

### ISSUE THREAD

**Issue by ryandw11** [imWillX/CrateReloaded#30]
My players have been having problems opening crates on the Free version. When they normal click they say it doesn't work. Although some players were able to do it when they shift clicked. According to my players it said "You have opened a crate". If you need any other information just ask.

**Comment by imWillX** [comment]
Please disable protection forms around the crate.

Ex: World Guard Flags, Default MC spawn protection

**Comment by ryandw11** [comment]
Okay thanks for your help!
