### ISSUE TITLE
Use the %line% variable in the display lore

### ISSUE THREAD

**Issue by DanSpedey** [imWillX/CrateReloaded#39]
`display:(175 1 &a$500  &8&lVery_Commmon%line%&7Money)'`

It just does not give a lore, could we add empty lines please like you can on an item?
Thanks

**Comment by imWillX** [comment]
Hey there,

I'll be sure to check the line issue out. What do you mean empty lines like on an item?

**Comment by DanSpedey** [comment]
The %line% variable works on the lore of an item, was just saying it would be useful for the same to happen in the display item lore.
