### ISSUE TITLE
Minecraft Commands: Breaks Parsing

### ISSUE THREAD

**Issue by imWillX** [imWillX/CrateReloaded#42]
Default Minecraft Commands

Breaks Parsing
`- 'cmd:(/give %player% potion 3 0 {CustomPotionEffects:[{Id:8, Amplifier:1, Duration:2500}]}), chance:(15), display:(potion 1 &a3_LeapPotions! &f%chance%), broadcast:(%prefix%3 Leap Potions)'`

`execute %player% ~ ~ ~ Zombie ~0 ~1 ~0 {HandItems:[{id:diamond_axe},{id:diamond_sword}],ArmorItems:[{},{},{},{id:diamond_helmet}]}`

`give %player% potion 3 0 {CustomPotionEffects:[{Id:8, Amplifier:1, Duration:2500}], display:{Name:"Leap Potion", Lore:["Have Fun!!"]}}`

edit: Added more Strings

**Comment by imWillX** [comment]
![Test](http://i.imgur.com/0X2OzCz.png)

**Comment by MCTyler** [comment]
Fantastic!
