### ISSUE TITLE
With creative-control enabled and a key in your offhand (MC 1.9), it does not take a key immediately as soon as you open a crate.

### ISSUE THREAD

**Issue by mibby** [imWillX/CrateReloaded#50]
CrateReloaded 1.3.70
PaperSpigot dev 706
ProtocolLib dev 273
PermissionsEx 1.23.5-SNAPSHOT

With creative-control enabled and a key in your offhand (MC 1.9), it does not take a key immediately as soon as you open a CSGO crate. Instead, it takes from the stack once the rotation is finished or when you exit the window. Whereas if the keys were in your hotbar, it immediately takes the key.

**Comment by imWillX** [comment]
Possibly fixed as of latest version. Needs testing.
