### ISSUE TITLE
How do I know the version am running.

### ISSUE THREAD

**Issue by ABNGaming** [imWillX/CrateReloaded#54]
I bought the crate about 2 weeks ago and I wanna see what version am running now to see if its updated or not, because I had a bug where crate list doesnt work anymore and have to reinstall the plugin!

**Comment by mibby** [comment]
In console (or while you are OP in-game), type /version CrateReloaded.

**Comment by ABNGaming** [comment]
I have an issue then, sometimes when i do /cr list it says %list%
while I have crates setup in config and to make em work again I have to reinstall the whole plugin!

**Comment by imWillX** [comment]
Can you post your crate.yml?

**Comment by ABNGaming** [comment]
`############################################
# +---------------------------------------+#
# |         Config Revision 16            |#
# +---------------------------------------+#
############################################

VoteCrate:
    type: CSGOKEYCRATE
    displayName: '&c[&aVote Crate&c]'
    holographic:
        -
    preview:
        enabled: true
    buy:
        enabled: false
        cost: 0
    message:
        onOpen: '%prefix%You have opened a &c[&aVote Crate&c]'
        broadcast: ''
    key:
        item: 'Tripwire_Hook'
        enchantment: '300:1'
        name: '&c[&aVote crate key&c]'
        lore:
            - '&8Right click a key chest to obtain rewards!'
    effect:
        onOpenEffects: 'firework, DRINK'
        dormantEffects: 'happyVillager'
        dormantRoulette: 'WOOD_CLICK'
        onRouletteEnd: 'BAT_TAKEOFF'
    reward:
        minimumRewards: 1
        maximumRewards: 5
        rewards:
            - 'cmd:(/give %player% 331 64), chance:(11), display:(35:3 1 &b64_Redstone!)'
            - 'cmd:(/give %player% 264 10), chance:(11), display:(35:3 1 &b10_Diamonds!)'
            - 'cmd:(/give %player% 265 10), chance:(11), display:(35:3 1 &b10_Iron_Ingots!)'
            - 'cmd:(/give %player% 388 10), chance:(11), display:(35:3 1 &b10_Emeralds!)'
            - 'cmd:(/eco give %player% 10000), chance:(11), display:(35:3 1 &b10k!)'
            - 'cmd:(/give %player% 2 32), chance:(7), display:(35:10 1 &532_grass_blocks!)'
            - 'cmd:(/eco give %player% 30000), chance:(7), display:(35:10 1 &550k!)'
            - 'cmd:(/spawner give %player% Cow), chance:(7), display:(35:10 1 &5Cow_spawner!)'
            - 'cmd:(/addcredits %player% 50), chance:(7), display:(35:10 1 &550_mcMMO!)'
            - 'cmd:(/addcredits %player% 75), chance:(5), broadcast:(&aVote Crate &8>> &6 %player% &7opened a &aVote carte &7and got &d75 mcMMO), display:(35:6 1 &d75_mcMMO!)'
            - 'cmd:(/eco give %player% 60000), chance:(5), broadcast:(&aVote Crate &8>> &6 %player% &7opened a &aVote carte &7and got &d60k), display:(35:6 1 &d60k!)'
            - 'cmd:(/addcredits %player% 100), chance:(2), broadcast:(&aVote Crate &8>> &6 %player% &7opened a &aVote carte &7and got &4100 mcMMO), display:(35:14 1 &4100_mcMMO!)'
            - 'cmd:(/eco give %player% 100000), chance:(2), broadcast:(&aVote Crate &8>> &6 %player% &7opened a &aVote carte &7and got &4100k), display:(35:14 1 &4100k!)'
            - 'cmd:(/spawner give %player% Creeper), chance:(2), broadcast:(&aVote Crate &8>> &6 %player% &7opened a &aVote carte &7and got &4Creeper spawner), display:(35:14 1 &4Creeper_spawner!)'
            - 'cmd:(/addcredits %player% 100), cmd:(/eco give %player% 100000), cmd:(/spawner give %player% Creeper) chance:(1), broadcast:(&aVote Crate &8>> &6 %player% &7opened a &aVote carte &7and got &C&KII &eTHE GOLD BLOCK &c&kII), display:(41 1 &6???)'
LegendCrate:
    type: CSGOKEYCRATE
    displayName: '&c[&6Legendary Key&c]'
    holographic:
        -
    preview:
        enabled: true
    buy:
        enabled: false
        cost: 0
    message:
        onOpen: '%prefix%You have opened a &c[&6Legendary Crate&c]'
        broadcast: ''
    key:
        item: 'tripwire_hook'
        enchantment: '300:1'
        name: '&c[&6Legendary Key&c]'
        lore:
            - '&8Right click a key chest to obtain rewards!'
    effect:
        onOpenEffects: 'firework, DRINK'
        dormantEffects: 'happyVillager'
        dormantRoulette: 'WOOD_CLICK'
        onRouletteEnd: 'BAT_TAKEOFF'
    reward:
        minimumRewards: 1
        maximumRewards: 5
        rewards:
            - 'cmd:(/spawner give %player% sheep), chance:(7), broadcast:(&6Legendary Crate &8>> &6 %player% &7opened a &6Legendary Crate &7and got &bSheep Spawner), display:(35:3 1 &bSheep_Spawner!)'
            - 'cmd:(/spawner give %player% creeper), chance:(7), broadcast:(&6Legendary Crate &8>> &6 %player% &7opened a &6Legendary Crate &7and got &bCreeper Spawner), display:(35:3 1 &bCreeper_Spawner!)'
            - 'cmd:(/spawner give %player% Cow), chance:(7), broadcast:(&6Legendary Crate &8>> &6 %player% &7opened a &6Legendary Crate &7and got &bCow Spawner), display:(35:3 1 &bCow_Spawner!)'
            - 'cmd:(/kit emerald %player%), chance:(7), broadcast:(&6Legendary Crate &8>> &6 %player% &7opened a &6Legendary Crate &7and got &bKit Emerald), display:(35:3 1 &bKit_Emerald!)'
            - 'cmd:(/addcredits %player% 100), chance:(7), broadcast:(&6Legendary Crate &8>> &6 %player% &7opened a &6Legendary Crate &7and got &b100 mcMMO), display:(35:3 1 &b100_mcMMO!)'
            - 'cmd:(/eco give %player% 250000), chance:(7), broadcast:(&6Legendary Crate &8>> &6 %player% &7opened a &6Legendary Crate &7and got &b250k), display:(35:3 1 &b250k!)'
            - 'cmd:(/spawner give %player% spider 2), chance:(7), broadcast:(&6Legendary Crate &8>> &6 %player% &7opened a &6Legendary Crate &7and got &b2 Spider Spawners), display:(35:3 1 &b2_Spider_Spawners!)'
            - 'cmd:(/spawner give %player% blaze), cmd:(/spawner give %player% witch), cmd:(/spawner give %player% mooshroom), cmd:(/spawner give %player% Rabbit), chance:(5), broadcast:(&6Legendary Crate &8>> &6 %player% &7opened a &6Legendary Crate &7and got &5a Hoi Spawner Pack), display:(35:10 1 &5a_Hoi_Spawner_Pack!)'
            - 'cmd:(/addcredits %player% 50), chance:(5), broadcast:(&6Legendary Crate &8>> &6 %player% &7opened a &6Legendary Crate &7and got &51 Diamond Crate Key), display:(35:10 1 &5Diamond_Crate_Key!)'
            - 'cmd:(/crate givekey %player% specialcrate 5), chance:(5), broadcast:(&6Legendary Crate &8>> &6 %player% &7opened a &6Legendary Crate &7and got &55Special Crate Keys), display:(35:10 1 &55_Special_Crate_Keys!)'
            - 'cmd:(/eco give %player% 500000), chance:(5), broadcast:(&aVote Crate &8>> &6 %player% &7opened a &aVote carte &7and got &5500k), display:(35:10 1 &5500k!)'
            - 'cmd:(/addcredits %player% 250), chance:(5), broadcast:(&aVote Crate &8>> &6 %player% &7opened a &aVote carte &7and got &5250 mcMMO), display:(35:10 1 &5250_mcMMO!)'
            - 'cmd:(/eco give %player% 4000000), chance:(4), broadcast:(&aVote Crate &8>> &6 %player% &7opened a &aVote carte &7and got &d4000000), display:(35:6 1 &d4mil!)'
            - 'cmd:(/addcredits %player% 450), chance:(4), broadcast:(&aVote Crate &8>> &6 %player% &7opened a &aVote carte &7and got &d450 mcMMO), display:(35:6 1 &d450_mcMMO!)'
            - 'cmd:(/eco give %player% 4000000), chance:(4), broadcast:(&aVote Crate &8>> &6 %player% &7opened a &aVote carte &7and got &dKit Legend), display:(35:6 1 &dKit_Legend!)'
            - 'cmd:(/crate givekey %player% legendcrate 2), chance:(4), broadcast:(&aVote Crate &8>> &6 %player% &7opened a &aVote carte &7and got &d2 Legendary Keys), display:(35:6 1 &d2_Legendary_Keys!)'
            - 'cmd:(/spawner give %player% IronGolem), chance:(3), broadcast:(&aVote Crate &8>> &6 %player% &7opened a &aVote carte &7and got &4Iron Golem Spawner), display:(35:14 1 &4Iron_Golem_spawner!)'
            - 'cmd:(/eco give %player% 7000000), chance:(3), broadcast:(&aVote Crate &8>> &6 %player% &7opened a &aVote carte &7and got &47mil), display:(35:14 1 &47mil!)'
            - 'cmd:(/addcredits %player% 750), chance:(3), broadcast:(&aVote Crate &8>> &6 %player% &7opened a &aVote carte &7and got &4750 mcMMO), display:(35:14 1 &4750_mcMMO!)'
            - 'cmd:(/spawner give %player% IronGolem), cmd:(/eco give %player% 7000000), cmd:(/addcredits %player% 750) chance:(1), broadcast:(&aVote Crate &8>> &6 %player% &7opened a &aVote carte &7and got &C&KII &eTHE GOLD BLOCK &c&kII), display:(41 1 &6???)'
SpecialCrate:
    type: CSGOKEYCRATE
    displayName: '&c[&dSpecial Crate&c]'
    holographic:
        -
    preview:
        enabled: true
    buy:
        enabled: false
        cost: 0
    message:
        onOpen: '%prefix%You have opened a &c[&dSpecial Crate&c]'
        broadcast: ''
    key:
        item: 'Tripwire_Hook'
        enchantment: '300:1'
        name: '&c[&dSpecial crate key&c]'
        lore:
            - '&8Right click a key chest to obtain rewards!'
    effect:
        onOpenEffects: 'firework, DRINK'
        dormantEffects: 'happyVillager'
        dormantRoulette: 'WOOD_CLICK'
        onRouletteEnd: 'BAT_TAKEOFF'
    reward:
        minimumRewards: 1
        maximumRewards: 5
        rewards:
            - 'cmd:(/give %player% 41 32), chance:(7), display:(35:3 1 &b32_Gold_Blocks!)'
            - 'cmd:(/give %player% 57 16), chance:(7), display:(35:3 1 &b16_Diamond_Blocks!)'
            - 'cmd:(/give %player% 22 128), chance:(7), display:(35:3 1 &b128_lapis_Blocks!)'
            - 'cmd:(/give %player% 42 64), chance:(7), display:(35:3 1 &b64_Iron_Blocks!)'
            - 'cmd:(/eco give %player% 25000), chance:(7), display:(35:3 1 &b25k!)'
            - 'cmd:(/addcredits %player% 25), chance:(7), display:(35:3 1 &b25_mcMMO!)'
            - 'cmd:(/spawner give %player% Cow), chance:(7), display:(35:3 1 &bCow_spawner!)'
            - 'cmd:(/spawner give %player% enderman), chance:(6), display:(35:10 1 &5Cow_Enderman!)'
            - 'cmd:(/addcredits %player% 75), chance:(6), display:(35:10 1 &575_mcMMO!)'
            - 'cmd:(/eco give %Player% 50000), chance:(6), display:(35:10 1 &d50k!)'
            - 'cmd:(/spawner give %player% sheep), chance:(6), display:(35:6 1 &dSheep_Spawner!)'
            - 'cmd:(/kit Diamond %player%), chance:(6), display:(35:6 1 &dKit_Diamond!)'
            - 'cmd:(/spawner give %player% guardian), chance:(4), broadcast:(&aSpecial Crate &8>> &6 %player% &7opened a &dSpecial crate &7and got &4100k), display:(35:6 1 &dGuardian_spawner!)'
            - 'cmd:(/spawner give %player% Creeper), chance:(4), broadcast:(&aSpecial Crate &8>> &6 %player% &7opened a &dSpecial crate &7and got &4Creeper spawner), display:(35:6 1 &dCreeper_spawner!)'
            - 'cmd:(/spawner give %player% Zombie), chance:(4), broadcast:(&aSpecial Crate &8>> &6 %player% &7opened a &dSpecial crate &7and got &4Creeper spawner), display:(35:6 1 &dZombie_spawner!)'
            - 'cmd:(/spawner give %player% Skeleton), chance:(4), broadcast:(&aSpecial Crate &8>> &6 %player% &7opened a &dSpecial crate &7and got &4Creeper spawner), display:(35:6 1 &dSkeleton_spawner!)'
            - 'cmd:(/spawner give %player% Creeper 5), chance:(2), broadcast:(&aSpecial Crate &8>> &6 %player% &7opened a &dSpecial crate &7and got &4Creeper spawner), display:(35:14 1 &45_Creeper_spawners!)'
            - 'cmd:(/kit bedrock %player%), chance:(2), broadcast:(&aSpecial Crate &8>> &6 %player% &7opened a &dSpecial crate &7and got &4Creeper spawner), display:(35:14 1 &4Kit_Bedrock!)'
            - 'cmd:(/eco give %player% 450000), chance:(2), broadcast:(&aSpecial Crate &8>> &6 %player% &7opened a &dSpecial crate &7and got &4Creeper spawner), display:(35:14 1 &4450k!)'
            - 'cmd:(/spawner give %player% Creeper 5), cmd:(/kit bedrock %player%), cmd:(/eco give %player% 450000) chance:(1), broadcast:(&aSpecial Crate &8>> &6 %player% &7opened a &dSpecial crate &7and got &C&KII &eTHE GOLD BLOCK &c&kII), display:(41 1 &6???)'`

**Comment by imWillX** [comment]
@ABNGaming 
Pastebin please. Need the original formatting.

**Comment by imWillX** [comment]
Closed, no reply.

Please reopen the issue if you need help.
