### ISSUE TITLE
"An internal error occurred while attempting to perform this plugin" 

### ISSUE THREAD

**Issue by afesraca** [imWillX/CrateReloaded#58]
#49  i try to use any commend, I get "An internal error occurred while attempting to perform this plugin" I use spigot 1.8.8 and the console says
`19.05 13:02:25 [Server] WARN at java.lang.Thread.run(Thread.java:745)
19.05 13:02:25 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
19.05 13:02:25 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
19.05 13:02:25 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
19.05 13:02:25 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
19.05 13:02:25 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
19.05 13:02:25 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
19.05 13:02:25 [Server] WARN at Messager.NoGapMessager.run(NoGapMessager.java:68)
19.05 13:02:25 [Server] WARN at Utils.General.setStatus(General.java:57)
19.05 13:02:25 [Server] WARN at Utils.v1_7.getTeleportPacket(v1_7.java:168)
19.05 13:02:25 [Server] WARN at java.lang.Class.getConstructor(Class.java:1825)
19.05 13:02:25 [Server] WARN at java.lang.Class.getConstructor0(Class.java:3082)
19.05 13:02:25 [Server] WARN java.lang.NoSuchMethodException: net.minecraft.server.v1_8_R3.PacketPlayOutEntityTeleport.<init>(int, int, int, int, byte, byte)
19.05 13:02:23 [Server] INFO world and player data has been saved.
19.05 13:02:15 [Server] WARN at java.lang.Thread.run(Thread.java:745)
19.05 13:02:15 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
19.05 13:02:15 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
19.05 13:02:15 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
19.05 13:02:15 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
19.05 13:02:15 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
19.05 13:02:15 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
19.05 13:02:15 [Server] WARN at Messager.NoGapMessager.run(NoGapMessager.java:68)
19.05 13:02:15 [Server] WARN at Utils.General.setStatus(General.java:57)
19.05 13:02:15 [Server] WARN at Utils.v1_7.getTeleportPacket(v1_7.java:168)
19.05 13:02:15 [Server] WARN at java.lang.Class.getConstructor(Class.java:1825)
19.05 13:02:15 [Server] WARN at java.lang.Class.getConstructor0(Class.java:3082)
19.05 13:02:15 [Server] WARN java.lang.NoSuchMethodException: net.minecraft.server.v1_8_R3.PacketPlayOutEntityTeleport.<init>(int, int, int, int, byte, byte)
19.05 13:02:13 [Server] INFO ... 15 more
19.05 13:02:13 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
19.05 13:02:13 [Server] INFO at cratereloaded.aB.onCommand(CommandManager.java:84) ~[?:?]
19.05 13:02:13 [Server] INFO at cratereloaded.aB.b(CommandManager.java:158) ~[?:?]
19.05 13:02:13 [Server] INFO at cratereloaded.bL.a(Messenger.java:24) ~[?:?]
19.05 13:02:13 [Server] INFO at cratereloaded.bD.b(FormatUtil.java:129) ~[?:?]
19.05 13:02:13 [Server] INFO at cratereloaded.bE.C(Formatter.java:47) ~[?:?]
19.05 13:02:13 [Server] INFO at cratereloaded.bE.E(Formatter.java:120) ~[?:?]
19.05 13:02:13 [Server] INFO at cratereloaded.aD.j(EconomyManager.java:67) ~[?:?]
19.05 13:02:13 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.milkbowl.vault.economy.Economy.getBalance(Lorg/bukkit/OfflinePlayer;)D
19.05 13:02:13 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
19.05 13:02:13 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
19.05 13:02:13 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
19.05 13:02:13 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
19.05 13:02:13 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
19.05 13:02:13 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
19.05 13:02:13 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
19.05 13:02:13 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
19.05 13:02:13 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
19.05 13:02:13 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
19.05 13:02:13 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
19.05 13:02:13 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
19.05 13:02:13 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
19.05 13:02:13 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
19.05 13:02:13 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
19.05 13:02:13 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
19.05 13:02:13 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'cr' in plugin CrateReloaded v1.3.69
19.05 13:02:13 [Server] ERROR null
19.05 13:02:05 [Server] WARN at java.lang.Thread.run(Thread.java:745)
19.05 13:02:05 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
19.05 13:02:05 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
19.05 13:02:05 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
19.05 13:02:05 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
19.05 13:02:05 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
19.05 13:02:05 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
19.05 13:02:05 [Server] WARN at Messager.NoGapMessager.run(NoGapMessager.java:68)
19.05 13:02:05 [Server] WARN at Utils.General.setStatus(General.java:57)
19.05 13:02:05 [Server] WARN at Utils.v1_7.getTeleportPacket(v1_7.java:168)
19.05 13:02:05 [Server] WARN at java.lang.Class.getConstructor(Class.java:1825)
19.05 13:02:05 [Server] WARN at java.lang.Class.getConstructor0(Class.java:3082)
19.05 13:02:05 [Server] WARN java.lang.NoSuchMethodException: net.minecraft.server.v1_8_R3.PacketPlayOutEntityTeleport.<init>(int, int, int, int, byte, byte)
19.05 13:01:57 [Server] INFO Kurucu: [Kurucu] afesraca
19.05 13:01:57 [Server] INFO Oyuncu Kapasitesi 1 Acik Olan 1,000.
19.05 13:01:55 [Server] WARN at java.lang.Thread.run(Thread.java:745)
19.05 13:01:55 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
19.05 13:01:55 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
19.05 13:01:55 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
19.05 13:01:55 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
19.05 13:01:55 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
19.05 13:01:55 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
19.05 13:01:55 [Server] WARN at Messager.NoGapMessager.run(NoGapMessager.java:68)
19.05 13:01:55 [Server] WARN at Utils.General.setStatus(General.java:57)
19.05 13:01:55 [Server] WARN at Utils.v1_7.getTeleportPacket(v1_7.java:168)
19.05 13:01:55 [Server] WARN at java.lang.Class.getConstructor(Class.java:1825)
19.05 13:01:55 [Server] WARN at java.lang.Class.getConstructor0(Class.java:3082)
19.05 13:01:55 [Server] WARN java.lang.NoSuchMethodException: net.minecraft.server.v1_8_R3.PacketPlayOutEntityTeleport.<init>(int, int, int, int, byte, byte)
19.05 13:01:55 [Multicraft] Skipped 12 lines due to rate limit (30/s)
19.05 13:01:45 [Server] WARN java.lang.NoSuchMethodException: net.minecraft.server.v1_8_R3.PacketPlayOutEntityTeleport.<init>(int, int, int, int, byte, byte)
19.05 13:01:45 [Server] INFO ... 15 more
19.05 13:01:45 [Server] INFO at org.bukkit.command.PluginCommand.execut`

**Comment by afesraca** [comment]
Help meeeee

**Comment by imWillX** [comment]
Update the plugin

**Comment by afesraca** [comment]
I uptade it but it doesn't work :(

**Comment by afesraca** [comment]
cry cry ;(
