### ISSUE TITLE
Exit GUI when item is still rolling

### ISSUE THREAD

**Issue by simux98** [imWillX/CrateReloaded#59]
Hello, so I tried CrateReloaded plugin, and it was the best I've ever tried, but there is a bug. When the system is still rolling the prize, you are able to exit that GUI table and receive ant item. But when you are trying to click it through inventory, it's just disappears. By that, I really wanted to see this fixed with some kind of blocking from exiting method in free version.

**Comment by imWillX** [comment]
Can you post an image.
