### ISSUE TITLE
Crates reloaded - Feature Request

### ISSUE THREAD

**Issue by VicZk** [imWillX/CrateReloaded#62]
Hello there! I would like to give you two suggestions, they are small things.
1 - Be able to Rename the glass (When the crate is rolling)
Config Example:

Glass Name:
-  'Rolling...'

2 Be able to change this items (http://prntscr.com/bd6edc) in the CS:GO  #Crate

Thank you!
~VicZk

**Comment by imWillX** [comment]
Closed: https://www.spigotmc.org/resources/mystery-crate-cratereloaded-for-the-finest-servers.3663/update?update=112796
