### ISSUE TITLE
Cooldown message outputs twice when right clicking a crate during cooldown phase.

### ISSUE THREAD

**Issue by mibby** [imWillX/CrateReloaded#67]
Spigot 1.10
CrateReloaded Premium 1.3.73

![link](http://i.imgur.com/CcQ7UPq.png)

I assume you are listening for any right click event instead of specifying a specific hand / item? Double output in other plugins have typically been due to the offhand added in 1.9. WorldGuard recently pushed a fix for a double output issue here. 
https://github.com/sk89q/WorldGuard/commit/15a9c50ea4c1fbf2c3c0b096d2c691527f01320b

**Comment by imWillX** [comment]
Thanks Mibby. I thought right clicking had no delay thus double output occurs.

**Comment by imWillX** [comment]
Fixed, will be released in next update.
