### ISSUE TITLE
Config not doing anything

### ISSUE THREAD

**Issue by JonathanVil** [imWillX/CrateReloaded#71]
Hey Guys! I have just installed CratesReloaded to my 1.9.4 Spigot server, and configured the crates. A strange thing is that the config.yml doesn't seem to change anything. If I for example change prefix in the config.yml, nothing happens ingame. If I change the pushbackEnabled, it doesn't change anything. I reload ingame, it gives me the reload complete message, but still no change. Please help!

**Comment by imWillX** [comment]
Hey there, 

May I ask what CrateReloaded version you are using?

**Comment by imWillX** [comment]
Will be closed in one day if there is no response from OP.

**Comment by JonathanVil** [comment]
1.3.26

**Comment by imWillX** [comment]
This version doesn't support changing prefix. 

We also cache language messages so you would have to /cr reloadlocale.

**Comment by JonathanVil** [comment]
So I would have to buy the premium version?

tor. 16. jun. 2016 kl. 09.02 skrev Dinosaur <notifications@github.com>:

**Comment by imWillX** [comment]
No, you can change it in the message file.
