### ISSUE TITLE
Error when creating crates

### ISSUE THREAD

**Issue by VicZk** [imWillX/CrateReloaded#72]
Hello there! I've been using the most recent version of CratesReloaded in Spigot 1.8.8 and whenever I try to create a crate, and open it, the error on the zip file appears, I also have my config in there (Test config)

[CR Bugs.zip](https://github.com/imWillX/CrateReloaded/files/321586/CR.Bugs.zi)

**Comment by imWillX** [comment]
Hello there, please use pastebin for all configs.

**Comment by VicZk** [comment]
Sure thing!
Config: http://pastebin.com/5c6WdbN1
Error: http://pastebin.com/LvnMCrA3

**Comment by imWillX** [comment]
Closed. If issue appears, please reopen issue.
