### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Devillion** [imWillX/CrateReloaded#76]
Would you be able to add a feature that allows us to put cooldowns on opening crates that use keys to open?

**Comment by imWillX** [comment]
Available in the premium version. Has not yet been ported to the free version.

**Comment by Devillion** [comment]
I have the premium version and I looked all through your online guide and couldn't find any settings for putting a cooldown.

How do you do this?

**Comment by imWillX** [comment]
It is inside your config.yml. There is a cooldown section. If not, backup, and delete your config.yml and let it regenerate. 

If you need any more help regarding this, feel free to reopen the issue.
