### ISSUE TITLE
[Client Crash] CS GO Crate crashes Clients

### ISSUE THREAD

**Issue by Rubbertjuh** [imWillX/CrateReloaded#78]
Hello and thank you for reading this,

On a rare occasion, when a user will activate the key on the crate, after a little while, the client will crash. This is the error that the user will have in his/her log.
http://hastebin.com/picosecoba.cs
There was no error in the console, just a regular disconnect.

I'm running version:  Latest: 1.3.77 (Premium)
CB Version: 1.7.10 Thermos (Modded server)

It looked like the Glass panes just bugged out and crashed the client, I'm not entirely sure though.
If I can provide more debug information, please do tell me.

**Comment by imWillX** [comment]
Hey RubbertJuh,

Are you perhaps using custom enchantments on some rewards? These are incompatible with Minecraft Version 1.7.10.

From the logs, it appears you are giving an item that is incompatible with the client. This may come from a rare reward which you mentioned that this happens on a "rare occasion".
