### ISSUE TITLE
Cauldron Particles Support

### ISSUE THREAD

**Issue by Rubbertjuh** [imWillX/CrateReloaded#89]
Heey,

As discussed in PM, it would be really cool if you could make particles work with Thermos(Cauldron). Instead of using packets, you will need to make a call for the Bukkit API, this will make it compatible with modded servers.
If this will be added, I will make sure to donate a nice amount for your time and dedication. 
Thank you in advance. Looking forward to this.

**Comment by imWillX** [comment]
#95 Sponge port that we talked about? (future)

**Comment by Rubbertjuh** [comment]
Yes please ^.^
