### ISSUE TITLE
NPC/MOB instead of blocks for crates

### ISSUE THREAD

**Issue by maxlehot1234** [imWillX/CrateReloaded#9]
Hi, is it possible to add a slime, creeper, skeleton, villager or anything else to allow player to righ-click it to use their keys for example.

For the moment, we used chest/blocks, but it can be very nice to see npc or mob support ;)

Thank you

**Comment by iAmWillX** [comment]
Interesting, I like this idea.

**Comment by maxlehot1234** [comment]
With this, I can put a big slime at the spawn so players can use their key on it to get rewards.
This slime works for all keys I set on it. Instewad of using 10 chest for 10 keys, I cna use 1 big slime, with particle effect and sound when the player get the rewards or click on the slime.

It was better and looks great on a server :)

**Comment by maxlehot1234** [comment]
Any news for this, because this can be nice ;)

**Comment by iAmWillX** [comment]
I'm currently working toward Supply Drops.

Working on a library for ingame menus.

**Comment by imWillX** [comment]
Will be released in the next update.
