### ISSUE TITLE
Invetory Slots?

### ISSUE THREAD

**Issue by Reeferx7** [imWillX/CrateReloaded#93]
Is possible to remove empty slots from crate preview inventory?

![30cde8381b6d1704eff2b12eaa39c54b](https://cloud.githubusercontent.com/assets/8740881/20554318/d3879350-b163-11e6-864f-9ba7a2d25e70.png)

Example in this case i want to keep only the first 9 slots and not 27.

**Comment by Twi5TeD** [comment]
It is possible but will hasn't added it

**Comment by imWillX** [comment]
Will be added in next update.
`
    preview:
        enabled: true
        rows: 1`
