### ISSUE TITLE
How to Make Colored Armor Prizes+Prize Lores?

### ISSUE THREAD

**Issue by AM4Z3** [imWillX/CrateReloaded#94]
Hello everybody, I am an admin on a server. The server is currently in its Alpha phase, but things are really coming together well. The server will probably go live in about a month, so we are working on Vote Crates and the website now. We have CrateReloaded premium, and we were wondering how we can make colored leather armor as prizes. I used Vanilla commands to make armor sets that give you particles and buffs, and some of the sets have customs lores and colors. (They are leather.) I was wondering how to implement both of these things into the crates. Thanks! -AM4Z3

**Comment by imWillX** [comment]
Please read your PMs.
