### ISSUE TITLE
Support for 1.11+ Mob Eggs

### ISSUE THREAD

**Issue by mibby** [imWillX/CrateReloaded#96]

**Comment by imWillX** [comment]
Mob eggs aren't working on spigot 1.11. Please update to spigot 1.11.2.

This occurred when I was running the spigot version off tcpr.ca.

**Comment by mibby** [comment]
What this ticket represented was adding support for the new mob egg types. :P Since I believe CrateReloaded uses a unique form of remapping to identify eggs in a rotation. (No separate IDs anymore in minecraft.)

**Comment by imWillX** [comment]
What do you mean by new mob egg types? Also, what do you mean by "no seperate IDs anymore in minecraft"? 

I think I have some catching up to do...

**Comment by mibby** [comment]
New mob egg types for the new mobs implemented in 1.11. Llama, Vex, Evoker, Vindicator, Zombie villager spawn egg, etc.

Since 1.9, minecraft has been deprecating numeric data ids. You can no longer spawn in a specific mob egg using the legacy id 383:50 to spawn in a creeper egg for example. So, how would the new 1.11 mob eggs be defined in a crate rotation? You might need some form of remapping or allow specifying by entity name?

**Comment by imWillX** [comment]
Thanks, i'll take a look into this.

**Comment by mibby** [comment]
Will also need to map 1.12 entity ids to their corresponding mob egg. Such as illusioner and parrot.

**Comment by imWillX** [comment]
Will be fixed in v1.3.97

Add a example config if you would like to test it out... 115d7a7
